DROP TABLE tasks IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 1;

CREATE TABLE tasks
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    description VARCHAR(10000)          NOT NULL,
    added       TIMESTAMP DEFAULT now() NOT NULL,
    modified    TIMESTAMP,
    completed   TIMESTAMP,
    CONSTRAINT chk_modified CHECK (modified IS NULL OR modified > added),
    CONSTRAINT chk_completed CHECK (completed IS NULL OR (completed > added AND completed > modified))
);